### ISSUE TITLE
The data analysis sample is not working

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular-samples#3599]
Go to https://www.infragistics.com/angular-demos-lob/grid-dynamic-chart-data/data-analysis-dock-manager

Notice that the data analysis extension does not render upon selection in the grid, and selecting a chart from the right-hand menu throws an exception.

**Comment by kdinev** [comment]
@zdrawku The chart types are now not visible on the right-hand side.

**Comment by zdrawku** [comment]
Both are addressed now:


![Image](https://github.com/user-attachments/assets/889e4ddc-4eae-4217-a254-2c3ce7bcec01)

**Comment by kdinev** [comment]
@zdrawku The conditional formatting tab in the adorner is now disabled and I cannot apply any formatting to my grid selection any more: 

![Image](https://github.com/user-attachments/assets/756e568a-a44b-4aa8-b112-1eafaf7cc97e)

**Comment by kdinev** [comment]
Upon further testing, the spawned charts no longer update after changing the selection range in the grid.

**Comment by radomirchev** [comment]
@zdrawku @dobromirts Sample is still not fixed. As a user I expect when select data to be able either to create chart or apply conditional formatting. Once chart is created, I expect the chart to be updated when I select different data.

**Comment by zdrawku** [comment]
@kdinev @radomirchev the sample is fixed now and the majority of the issues we identified prior and during the testing are covered.

Topic: https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/data-analysis#data-analysis-with-dockmanager

Sample in full screen: https://www.infragistics.com/angular-demos-lob/grid-dynamic-chart-data/data-analysis-dock-manager

**Comment by radomirchev** [comment]
@zdrawku here is a gif, that shows the full sample capabilities. You can use it to match the current sample state:

![Image](https://github.com/user-attachments/assets/86f5bc15-5c05-43ca-9f5e-c77770b71a88)

**Comment by radomirchev** [comment]
Upon selecting new data, the prime color of the series of some charts (pie chart is behaving ok), became uniform for all series and it gets impossible to make difference between them. Second, I notice that behavior - the data in the charts is refreshed only on click after selecting new data.

![Image](https://github.com/user-attachments/assets/a7a83e7c-4845-46dc-9adf-313b7a6fd58b)

**Comment by hanastasov** [comment]
> Upon selecting new data, the prime color of the series of some charts (pie chart is behaving ok), became uniform for all series and it gets impossible to make difference between them. Second, I notice that behavior - the data in the charts is refreshed only on click after selecting new data.
> 
> ![Image](https://github.com/user-attachments/assets/a7a83e7c-4845-46dc-9adf-313b7a6fd58b) [ ![Image](https://github.com/user-attachments/assets/a7a83e7c-4845-46dc-9adf-313b7a6fd58b) ](https://private-user-images.githubusercontent.com/52001020/419840564-a7a83e7c-4845-46dc-9adf-313b7a6fd58b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDI4MTEwMzQsIm5iZiI6MTc0MjgxMDczNCwicGF0aCI6Ii81MjAwMTAyMC80MTk4NDA1NjQtYTdhODNlN2MtNDg0NS00NmRjLTlhZGYtMzEzYjdhNmZkNThiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzI0VDEwMDUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3NTIwMjZiZGFkYmE2NTUxODIxMmVjZmRkODk5YWM4NTFhOTY3OGEzMjg0ZmZiOWU1ZDEyYjM2ZGI1OWJhMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._Svo_ELeS6oRuLF_ApemdG7nSR6O6hHKrXSpmMEO5QI) [ ](https://private-user-images.githubusercontent.com/52001020/419840564-a7a83e7c-4845-46dc-9adf-313b7a6fd58b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDI4MTEwMzQsIm5iZiI6MTc0MjgxMDczNCwicGF0aCI6Ii81MjAwMTAyMC80MTk4NDA1NjQtYTdhODNlN2MtNDg0NS00NmRjLTlhZGYtMzEzYjdhNmZkNThiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzI0VDEwMDUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3NTIwMjZiZGFkYmE2NTUxODIxMmVjZmRkODk5YWM4NTFhOTY3OGEzMjg0ZmZiOWU1ZDEyYjM2ZGI1OWJhMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._Svo_ELeS6oRuLF_ApemdG7nSR6O6hHKrXSpmMEO5QI)

https://github.com/IgniteUI/igniteui-angular-samples/issues/3655
